name: Feature Request
description: Suggest an idea for this project
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explanation of the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are we doing this? What use cases does it support? What is the expected outcome?
  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: Suggest an idea for implementing the addition or change.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: markdown
    attributes:
      value: |
        ### Acknowledgements
        This Bug report template was taken from the excellent [PyBaMM](https://github.com/pybamm-team/PyBaMM) repository.
